// ─────────────────────────────────────────────────────────────────────────
// AFFIRMATIONS DATA
// This is the only file you need to touch to add, remove, or edit content.
//
// To add a category: add an entry to CATEGORIES with a unique `id`.
// To add an affirmation: add an entry to AFFIRMATIONS with a `category`
// that matches one of the CATEGORIES ids. That's it — it'll show up
// automatically in onboarding, home, and settings.
// ─────────────────────────────────────────────────────────────────────────

export const CATEGORIES = [
  { id: "confidence", label: "Confidence", emoji: "💪", color: "#6C4DFF" },
  { id: "calm", label: "Calm", emoji: "🌊", color: "#00BFA5" },
  { id: "gratitude", label: "Gratitude", emoji: "🌻", color: "#FFB300" },
  { id: "selflove", label: "Self-Love", emoji: "💗", color: "#FF6F91" },
  { id: "success", label: "Success", emoji: "🚀", color: "#448AFF" },
  { id: "resilience", label: "Resilience", emoji: "🔥", color: "#FF7043" },
  { id: "focus", label: "Focus", emoji: "🧠", color: "#9C27B0" },
  { id: "joy", label: "Joy", emoji: "✨", color: "#FFCA28" },
  { id: "creativity", label: "Creativity", emoji: "🎨", color: "#E91E63" },
];

export const AFFIRMATIONS = [
  // ───────────────────────────────────────────────────────────────────────
  // CONFIDENCE
  // ───────────────────────────────────────────────────────────────────────
  { id: "c1", category: "confidence", text: "I trust myself to make the right decisions." },
  { id: "c2", category: "confidence", text: "I am worthy of every opportunity that comes my way." },
  { id: "c3", category: "confidence", text: "My voice matters, and I speak up with ease." },
  { id: "c4", category: "confidence", text: "I walk into every room exactly as I am, and that's enough." },
  { id: "c5", category: "confidence", text: "I back myself, even when the outcome is uncertain." },
  { id: "c6", category: "confidence", text: "I am capable of figuring things out as I go." },
  { id: "c7", category: "confidence", text: "Confidence is a practice, and I get better at it every day." },
  { id: "c8", category: "confidence", text: "I don't need permission to take up space." },
  { id: "c9", category: "confidence", text: "I bring a unique perspective that the world needs." },
  { id: "c10", category: "confidence", text: "My intuition is a powerful guide." },
  { id: "c11", category: "confidence", text: "I am equipped to handle whatever today brings." },
  { id: "c12", category: "confidence", text: "I release the need for external validation." },
  { id: "c13", category: "confidence", text: "I am confident in my skills and my ability to learn new ones." },
  { id: "c14", category: "confidence", text: "I am my own best advocate." },
  { id: "c15", category: "confidence", text: "I deserve to be heard and respected." },
  { id: "c16", category: "confidence", text: "My boundaries are valid, and I enforce them with ease." },
  { id: "c17", category: "confidence", text: "I am comfortable being seen." },
  { id: "c18", category: "confidence", text: "I stand tall in my truth." },
  { id: "c19", category: "confidence", text: "I am not intimidated by the success of others." },
  { id: "c20", category: "confidence", text: "I project self-assurance in everything I do." },
  { id: "c21", category: "confidence", text: "My potential is entirely up to me to define." },
  { id: "c22", category: "confidence", text: "I give myself permission to be a beginner." },
  { id: "c23", category: "confidence", text: "I embrace challenges as stepping stones to greatness." },
  { id: "c24", category: "confidence", text: "I am an authority on my own life." },
  { id: "c25", category: "confidence", text: "My mere presence is powerful." },
  { id: "c26", category: "confidence", text: "I am unafraid of making mistakes; they help me grow." },
  { id: "c27", category: "confidence", text: "I am deeply secure in who I am." },
  { id: "c28", category: "confidence", text: "I replace self-doubt with self-belief." },
  { id: "c29", category: "confidence", text: "I have everything I need within me right now." },
  { id: "c30", category: "confidence", text: "I choose to be my own biggest cheerleader." },
  { id: "c31", category: "confidence", text: "I am magnetic when I am authentically myself." },
  { id: "c32", category: "confidence", text: "I step outside my comfort zone with courage." },
  { id: "c33", category: "confidence", text: "My ideas are innovative and valuable." },
  { id: "c34", category: "confidence", text: "I communicate my needs clearly and confidently." },
  { id: "c35", category: "confidence", text: "I am worthy of respect from myself and others." },
  { id: "c36", category: "confidence", text: "I trust my journey, even when I can't see the destination." },
  { id: "c37", category: "confidence", text: "I am unshakable in my self-worth." },
  { id: "c38", category: "confidence", text: "I celebrate my strengths and acknowledge my growth." },
  { id: "c39", category: "confidence", text: "I belong wherever I choose to be." },
  { id: "c40", category: "confidence", text: "I step into my power today and every day." },
  { id: "c41", category: "confidence", text: "I am constantly amazed by my own courage." },
  { id: "c42", category: "confidence", text: "My confidence inspires those around me." },
  { id: "c43", category: "confidence", text: "I embrace my uniqueness with total pride." },
  { id: "c44", category: "confidence", text: "I trust my inner voice above all others." },
  { id: "c45", category: "confidence", text: "I am ready to show the world what I can do." },

  // ───────────────────────────────────────────────────────────────────────
  // CALM
  // ───────────────────────────────────────────────────────────────────────
  { id: "l1", category: "calm", text: "I am allowed to slow down." },
  { id: "l2", category: "calm", text: "This moment is enough. I don't need to rush it." },
  { id: "l3", category: "calm", text: "I release what I cannot control and breathe easy." },
  { id: "l4", category: "calm", text: "Peace is available to me right now, in this breath." },
  { id: "l5", category: "calm", text: "I move through today at a pace that feels good." },
  { id: "l6", category: "calm", text: "My nervous system is learning to trust safety again." },
  { id: "l7", category: "calm", text: "I can be calm and still get everything done." },
  { id: "l8", category: "calm", text: "Stillness is productive too." },
  { id: "l9", category: "calm", text: "I inhale peace and exhale tension." },
  { id: "l10", category: "calm", text: "My mind is a clear, quiet lake." },
  { id: "l11", category: "calm", text: "I choose harmony over urgency." },
  { id: "l12", category: "calm", text: "I am rooted in the present moment." },
  { id: "l13", category: "calm", text: "I let go of the need to have all the answers right now." },
  { id: "l14", category: "calm", text: "My energy is grounded and steady." },
  { id: "l15", category: "calm", text: "I give myself grace on overwhelming days." },
  { id: "l16", category: "calm", text: "I create pockets of peace throughout my day." },
  { id: "l17", category: "calm", text: "I am safe, right here, right now." },
  { id: "l18", category: "calm", text: "I respond to stress with a deep breath." },
  { id: "l19", category: "calm", text: "I release the tension stored in my body." },
  { id: "l20", category: "calm", text: "I am the calm within the storm." },
  { id: "l21", category: "calm", text: "There is no emergency in this exact moment." },
  { id: "l22", category: "calm", text: "I let my thoughts pass by like clouds in the sky." },
  { id: "l23", category: "calm", text: "I invite serenity into my environment." },
  { id: "l24", category: "calm", text: "I am not responsible for fixing everything." },
  { id: "l25", category: "calm", text: "I give my mind permission to rest." },
  { id: "l26", category: "calm", text: "I detach from chaos and align with peace." },
  { id: "l27", category: "calm", text: "Every breath I take fills me with tranquility." },
  { id: "l28", category: "calm", text: "I am completely present in the here and now." },
  { id: "l29", category: "calm", text: "I choose to react with patience." },
  { id: "l30", category: "calm", text: "I soften my shoulders and unclench my jaw." },
  { id: "l31", category: "calm", text: "I trust that everything will unfold in its own time." },
  { id: "l32", category: "calm", text: "I prioritize my peace of mind." },
  { id: "l33", category: "calm", text: "I am a sanctuary of calm." },
  { id: "l34", category: "calm", text: "I let go of the day's worries." },
  { id: "l35", category: "calm", text: "I embrace the quiet spaces in my life." },
  { id: "l36", category: "calm", text: "My spirit is gentle and undisturbed." },
  { id: "l37", category: "calm", text: "I focus only on what is right in front of me." },
  { id: "l38", category: "calm", text: "I allow myself to simply exist." },
  { id: "l39", category: "calm", text: "I find comfort in the rhythm of my own breathing." },
  { id: "l40", category: "calm", text: "I am deeply relaxed and wonderfully calm." },
  { id: "l41", category: "calm", text: "I let the quiet wash over me like a gentle wave." },
  { id: "l42", category: "calm", text: "My mind is a safe and peaceful place to be." },
  { id: "l43", category: "calm", text: "I gently release all my worries to the wind." },
  { id: "l44", category: "calm", text: "I choose to be kind and gentle with my thoughts." },
  { id: "l45", category: "calm", text: "Everything is okay in this very second." },

  // ───────────────────────────────────────────────────────────────────────
  // GRATITUDE
  // ───────────────────────────────────────────────────────────────────────
  { id: "g1", category: "gratitude", text: "I notice the small good things — they add up." },
  { id: "g2", category: "gratitude", text: "There is always something today worth thanking." },
  { id: "g3", category: "gratitude", text: "I am grateful for how far I've already come." },
  { id: "g4", category: "gratitude", text: "Gratitude turns what I have into enough." },
  { id: "g5", category: "gratitude", text: "I appreciate the people who show up for me." },
  { id: "g6", category: "gratitude", text: "Even ordinary days hold something worth savoring." },
  { id: "g7", category: "gratitude", text: "I am thankful for my body and everything it lets me do." },
  { id: "g8", category: "gratitude", text: "I choose to see today as a gift, not a given." },
  { id: "g9", category: "gratitude", text: "I am grateful for a new day and a fresh start." },
  { id: "g10", category: "gratitude", text: "I find joy in the simple pleasures of life." },
  { id: "g11", category: "gratitude", text: "I am thankful for the roof over my head." },
  { id: "g12", category: "gratitude", text: "I give thanks for the food that nourishes me." },
  { id: "g13", category: "gratitude", text: "I am grateful for the challenges that help me grow." },
  { id: "g14", category: "gratitude", text: "I appreciate the beauty of nature around me." },
  { id: "g15", category: "gratitude", text: "I am thankful for the quiet moments of reflection." },
  { id: "g16", category: "gratitude", text: "I hold gratitude for my past and hope for my future." },
  { id: "g17", category: "gratitude", text: "I am blessed with unique talents and gifts." },
  { id: "g18", category: "gratitude", text: "I am thankful for the laughter I share with others." },
  { id: "g19", category: "gratitude", text: "I appreciate the modern conveniences that make my life easier." },
  { id: "g20", category: "gratitude", text: "I am grateful for the ability to learn and change." },
  { id: "g21", category: "gratitude", text: "I give thanks for the love I receive and the love I give." },
  { id: "g22", category: "gratitude", text: "I am thankful for my breath, which anchors me." },
  { id: "g23", category: "gratitude", text: "I appreciate the art, music, and stories that inspire me." },
  { id: "g24", category: "gratitude", text: "I am grateful for moments of unexpected kindness." },
  { id: "g25", category: "gratitude", text: "I give thanks for the health that I have today." },
  { id: "g26", category: "gratitude", text: "I am thankful for the freedom to make my own choices." },
  { id: "g27", category: "gratitude", text: "I appreciate the comfort of a warm bed." },
  { id: "g28", category: "gratitude", text: "I am grateful for the seasons and their changing beauty." },
  { id: "g29", category: "gratitude", text: "I give thanks for the mistakes that taught me valuable lessons." },
  { id: "g30", category: "gratitude", text: "I am thankful for my mind and its endless capacity." },
  { id: "g31", category: "gratitude", text: "I appreciate the memories that make me smile." },
  { id: "g32", category: "gratitude", text: "I am grateful for the friends who feel like family." },
  { id: "g33", category: "gratitude", text: "I give thanks for the opportunities lying ahead of me." },
  { id: "g34", category: "gratitude", text: "I am thankful for the ability to feel deeply." },
  { id: "g35", category: "gratitude", text: "I appreciate the peace I find when I slow down." },
  { id: "g36", category: "gratitude", text: "I am grateful for the sun that rises every single day." },
  { id: "g37", category: "gratitude", text: "I give thanks for the support systems in my life." },
  { id: "g38", category: "gratitude", text: "I am thankful for the small comforts that bring me joy." },
  { id: "g39", category: "gratitude", text: "I appreciate the privilege of simply being alive." },
  { id: "g40", category: "gratitude", text: "My heart is full of gratitude for the abundance around me." },
  { id: "g41", category: "gratitude", text: "I am thankful for the chance to learn and grow today." },
  { id: "g42", category: "gratitude", text: "I find something to be thankful for in every situation." },
  { id: "g43", category: "gratitude", text: "I deeply appreciate the people who make me smile." },
  { id: "g44", category: "gratitude", text: "My life is full of wonderful moments waiting to be noticed." },
  { id: "g45", category: "gratitude", text: "I say thank you for the strength I have built." },

  // ───────────────────────────────────────────────────────────────────────
  // SELF-LOVE
  // ───────────────────────────────────────────────────────────────────────
  { id: "s1", category: "selflove", text: "I am allowed to take care of myself without guilt." },
  { id: "s2", category: "selflove", text: "I speak to myself the way I'd speak to someone I love." },
  { id: "s3", category: "selflove", text: "I am not behind. I am exactly where I need to be." },
  { id: "s4", category: "selflove", text: "My worth was never up for debate." },
  { id: "s5", category: "selflove", text: "I forgive myself for what I didn't know back then." },
  { id: "s6", category: "selflove", text: "I am proud of who I'm becoming." },
  { id: "s7", category: "selflove", text: "Rest is something I deserve, not something I earn." },
  { id: "s8", category: "selflove", text: "I choose progress over perfection, always." },
  { id: "s9", category: "selflove", text: "I honor my body and its need for rest and nourishment." },
  { id: "s10", category: "selflove", text: "I am a masterpiece in progress." },
  { id: "s11", category: "selflove", text: "My feelings are valid, and I allow myself to feel them." },
  { id: "s12", category: "selflove", text: "I release the pressure to be anything other than myself." },
  { id: "s13", category: "selflove", text: "I am deserving of my own love and affection." },
  { id: "s14", category: "selflove", text: "I celebrate my individuality." },
  { id: "s15", category: "selflove", text: "I protect my energy and fiercely guard my peace." },
  { id: "s16", category: "selflove", text: "I am complete exactly as I am right now." },
  { id: "s17", category: "selflove", text: "I let go of past versions of myself with love." },
  { id: "s18", category: "selflove", text: "My self-worth is not tied to my productivity." },
  { id: "s19", category: "selflove", text: "I trust myself to honor my own needs." },
  { id: "s20", category: "selflove", text: "I am beautifully and wonderfully made." },
  { id: "s21", category: "selflove", text: "I give myself permission to evolve." },
  { id: "s22", category: "selflove", text: "I am patient with myself as I heal and grow." },
  { id: "s23", category: "selflove", text: "I treat myself with the kindness I readily give to others." },
  { id: "s24", category: "selflove", text: "I am entirely worthy of a beautiful life." },
  { id: "s25", category: "selflove", text: "I am my own longest commitment, and I choose to nurture it." },
  { id: "s26", category: "selflove", text: "I embrace my flaws; they make me human." },
  { id: "s27", category: "selflove", text: "I love the person looking back at me in the mirror." },
  { id: "s28", category: "selflove", text: "I do not need to shrink to fit into anyone else's expectations." },
  { id: "s29", category: "selflove", text: "I am enough, simply because I exist." },
  { id: "s30", category: "selflove", text: "I prioritize my mental health without apology." },
  { id: "s31", category: "selflove", text: "I look at myself with eyes of compassion." },
  { id: "s32", category: "selflove", text: "I am allowed to take up space and be loud." },
  { id: "s33", category: "selflove", text: "I celebrate the small victories of my daily life." },
  { id: "s34", category: "selflove", text: "I free myself from the burden of self-judgment." },
  { id: "s35", category: "selflove", text: "I deeply and completely accept myself." },
  { id: "s36", category: "selflove", text: "I fill my own cup first." },
  { id: "s37", category: "selflove", text: "I am grateful for the resilience of my own heart." },
  { id: "s38", category: "selflove", text: "I am writing a beautiful story for myself." },
  { id: "s39", category: "selflove", text: "I deserve to enjoy the fruits of my labor." },
  { id: "s40", category: "selflove", text: "My love for myself is unconditional." },
  { id: "s41", category: "selflove", text: "I am worthy of all the good things life has to offer." },
  { id: "s42", category: "selflove", text: "I embrace my journey and love who I am becoming." },
  { id: "s43", category: "selflove", text: "My self-care is a priority, not an option." },
  { id: "s44", category: "selflove", text: "I am my own best friend and greatest supporter." },
  { id: "s45", category: "selflove", text: "I shower myself with compassion and kindness." },

  // ───────────────────────────────────────────────────────────────────────
  // SUCCESS
  // ───────────────────────────────────────────────────────────────────────
  { id: "u1", category: "success", text: "Every small step today moves the bigger picture forward." },
  { id: "u2", category: "success", text: "I am building something real, one day at a time." },
  { id: "u3", category: "success", text: "Growth doesn't always look like winning, and that's okay." },
  { id: "u4", category: "success", text: "I am exactly the kind of person who follows through." },
  { id: "u5", category: "success", text: "My focus today is a gift to my future self." },
  { id: "u6", category: "success", text: "I define success on my own terms." },
  { id: "u7", category: "success", text: "I am capable of learning whatever this next step requires." },
  { id: "u8", category: "success", text: "Momentum starts with one small, doable action." },
  { id: "u9", category: "success", text: "I am a magnet for positive opportunities." },
  { id: "u10", category: "success", text: "I have the discipline to execute my vision." },
  { id: "u11", category: "success", text: "Success is a natural byproduct of my consistent effort." },
  { id: "u12", category: "success", text: "I am resourceful and capable of solving complex problems." },
  { id: "u13", category: "success", text: "I attract abundance in all areas of my life." },
  { id: "u14", category: "success", text: "I trust my unique timeline for success." },
  { id: "u15", category: "success", text: "I invest in myself because my future is worth it." },
  { id: "u16", category: "success", text: "I am continuously leveling up in my life." },
  { id: "u17", category: "success", text: "I release the fear of failure and embrace the joy of learning." },
  { id: "u18", category: "success", text: "My daily habits dictate my future success." },
  { id: "u19", category: "success", text: "I am worthy of the success I am working toward." },
  { id: "u20", category: "success", text: "I celebrate the success of others and know there is enough for me." },
  { id: "u21", category: "success", text: "I am bold in my ambitions." },
  { id: "u22", category: "success", text: "I possess the qualities needed to be extremely successful." },
  { id: "u23", category: "success", text: "I am open to new paths that lead to my goals." },
  { id: "u24", category: "success", text: "I take actionable steps toward my dreams every single day." },
  { id: "u25", category: "success", text: "I am not afraid to pivot when something isn't working." },
  { id: "u26", category: "success", text: "I trust that my hard work will pay off." },
  { id: "u27", category: "success", text: "I create value wherever I go." },
  { id: "u28", category: "success", text: "My mind is clear, focused, and ready to achieve." },
  { id: "u29", category: "success", text: "I am surrounded by people who uplift and inspire my growth." },
  { id: "u30", category: "success", text: "I confidently step into leadership." },
  { id: "u31", category: "success", text: "I embrace constructive feedback as a tool for growth." },
  { id: "u32", category: "success", text: "I believe in my ability to create a life I love." },
  { id: "u33", category: "success", text: "I am a continuous learner." },
  { id: "u34", category: "success", text: "I stay committed even when motivation fades." },
  { id: "u35", category: "success", text: "I visualize my success and actively move toward it." },
  { id: "u36", category: "success", text: "I am unbothered by temporary setbacks." },
  { id: "u37", category: "success", text: "I make decisions today that my future self will thank me for." },
  { id: "u38", category: "success", text: "My potential is limitless." },
  { id: "u39", category: "success", text: "I possess a wealth of knowledge and expertise." },
  { id: "u40", category: "success", text: "I am achieving greatness on my own timeline." },
  { id: "u41", category: "success", text: "I turn challenges into stepping stones." },
  { id: "u42", category: "success", text: "Every day brings me closer to my goals." },
  { id: "u43", category: "success", text: "I am capable of reaching heights I once only dreamed of." },
  { id: "u44", category: "success", text: "I trust my vision and stay dedicated to my path." },
  { id: "u45", category: "success", text: "Success flows to me effortlessly and naturally." },

  // ───────────────────────────────────────────────────────────────────────
  // RESILIENCE
  // ───────────────────────────────────────────────────────────────────────
  { id: "r1", category: "resilience", text: "I have survived every hard day so far — that's a track record." },
  { id: "r2", category: "resilience", text: "I can be soft and unbreakable at the same time." },
  { id: "r3", category: "resilience", text: "Setbacks are information, not verdicts." },
  { id: "r4", category: "resilience", text: "I keep going, even when it's slow." },
  { id: "r5", category: "resilience", text: "I am stronger than the thing that's testing me today." },
  { id: "r6", category: "resilience", text: "Hard seasons don't last forever, but I do." },
  { id: "r7", category: "resilience", text: "I've made it through 100% of my worst days." },
  { id: "r8", category: "resilience", text: "I get to decide what this moment means about me." },
  { id: "r9", category: "resilience", text: "I bend so that I do not break." },
  { id: "r10", category: "resilience", text: "I am anchored in my own inner strength." },
  { id: "r11", category: "resilience", text: "I transform adversity into power." },
  { id: "r12", category: "resilience", text: "Every challenge I face makes me wiser." },
  { id: "r13", category: "resilience", text: "I allow myself to rest, but I do not quit." },
  { id: "r14", category: "resilience", text: "I trust my ability to navigate tough times." },
  { id: "r15", category: "resilience", text: "I am a warrior in my own story." },
  { id: "r16", category: "resilience", text: "I can handle discomfort; it is temporary." },
  { id: "r17", category: "resilience", text: "I am not defined by my struggles, but by how I overcome them." },
  { id: "r18", category: "resilience", text: "I find courage even when I feel afraid." },
  { id: "r19", category: "resilience", text: "I rebuild stronger every time I fall." },
  { id: "r20", category: "resilience", text: "My spirit is profoundly resilient." },
  { id: "r21", category: "resilience", text: "I give myself permission to grieve what didn't work out." },
  { id: "r22", category: "resilience", text: "I hold onto hope, even in the dark." },
  { id: "r23", category: "resilience", text: "I breathe through the pain and emerge renewed." },
  { id: "r24", category: "resilience", text: "I trust that this difficult chapter is building my character." },
  { id: "r25", category: "resilience", text: "I am equipped to handle the unexpected." },
  { id: "r26", category: "resilience", text: "I forgive myself for days when just surviving is enough." },
  { id: "r27", category: "resilience", text: "I am rooted deeply and can withstand the storm." },
  { id: "r28", category: "resilience", text: "I refuse to let bitterness take hold of my heart." },
  { id: "r29", category: "resilience", text: "I am a survivor, and I am thriving." },
  { id: "r30", category: "resilience", text: "I seek support when I need it, and that makes me strong." },
  { id: "r31", category: "resilience", text: "I am capable of starting over as many times as it takes." },
  { id: "r32", category: "resilience", text: "I let go of the past and step bravely into the future." },
  { id: "r33", category: "resilience", text: "I find meaning and purpose in my healing journey." },
  { id: "r34", category: "resilience", text: "I trust the process of my own recovery." },
  { id: "r35", category: "resilience", text: "I am fiercely capable of protecting my own peace." },
  { id: "r36", category: "resilience", text: "I face reality head-on, with courage and grace." },
  { id: "r37", category: "resilience", text: "I am not broken; I am evolving." },
  { id: "r38", category: "resilience", text: "I allow failure to be a teacher, not an enemy." },
  { id: "r39", category: "resilience", text: "I honor my struggles and celebrate my endurance." },
  { id: "r40", category: "resilience", text: "I have an infinite capacity to overcome." },
  { id: "r41", category: "resilience", text: "I have the power to rise above any obstacle." },
  { id: "r42", category: "resilience", text: "My strength grows with every challenge I face." },
  { id: "r43", category: "resilience", text: "I bounce back quickly and with renewed energy." },
  { id: "r44", category: "resilience", text: "I am a beacon of perseverance and hope." },
  { id: "r45", category: "resilience", text: "Nothing can dim the light that shines from within me." },

  // ───────────────────────────────────────────────────────────────────────
  // FOCUS
  // ───────────────────────────────────────────────────────────────────────
  { id: "f1", category: "focus", text: "My mind is sharp and ready to learn." },
  { id: "f2", category: "focus", text: "I can tackle one task at a time with clarity." },
  { id: "f3", category: "focus", text: "Learning new things makes my brain stronger." },
  { id: "f4", category: "focus", text: "I am focused, motivated, and ready to do my best." },
  { id: "f5", category: "focus", text: "Challenges help me grow." },
  { id: "f6", category: "focus", text: "I am in charge of my attention." },
  { id: "f7", category: "focus", text: "My thoughts are organized and clear." },
  { id: "f8", category: "focus", text: "I am capable of deeply understanding new ideas." },
  { id: "f9", category: "focus", text: "Step by step, I am mastering my goals." },
  { id: "f10", category: "focus", text: "I embrace the process of learning." },
  { id: "f11", category: "focus", text: "I give my full attention to the present moment." },
  { id: "f12", category: "focus", text: "It is okay if I don't know the answer right away." },
  { id: "f13", category: "focus", text: "I am getting better and smarter every day." },
  { id: "f14", category: "focus", text: "I have the discipline to reach my targets." },
  { id: "f15", category: "focus", text: "I can do hard things if I take my time." },
  { id: "f16", category: "focus", text: "I am building healthy habits for my mind." },
  { id: "f17", category: "focus", text: "My potential to learn is limitless." },
  { id: "f18", category: "focus", text: "I block out distractions with ease." },
  { id: "f19", category: "focus", text: "I am proud of the effort I put into my work." },
  { id: "f20", category: "focus", text: "I ask questions because I want to grow." },

  // ───────────────────────────────────────────────────────────────────────
  // JOY
  // ───────────────────────────────────────────────────────────────────────
  { id: "j1", category: "joy", text: "I choose to look for the good in today." },
  { id: "j2", category: "joy", text: "My smile can light up a room." },
  { id: "j3", category: "joy", text: "I deserve to feel happy and carefree." },
  { id: "j4", category: "joy", text: "I find joy in the little things." },
  { id: "j5", category: "joy", text: "My heart is open to wonderful surprises today." },
  { id: "j6", category: "joy", text: "I radiate positive energy to those around me." },
  { id: "j7", category: "joy", text: "I am creating a life that feels good on the inside." },
  { id: "j8", category: "joy", text: "Laughter is my favorite way to recharge." },
  { id: "j9", category: "joy", text: "I attract kind and uplifting people." },
  { id: "j10", category: "joy", text: "I am allowed to have fun and be playful." },
  { id: "j11", category: "joy", text: "Joy is my natural state of being." },
  { id: "j12", category: "joy", text: "I celebrate the happiness of others." },
  { id: "j13", category: "joy", text: "Today is a great day to have a great day." },
  { id: "j14", category: "joy", text: "I let go of worry and invite in joy." },
  { id: "j15", category: "joy", text: "My happiness comes from within." },
  { id: "j16", category: "joy", text: "I sprinkle kindness everywhere I go." },
  { id: "j17", category: "joy", text: "I focus on thoughts that make me feel good." },
  { id: "j18", category: "joy", text: "I am a positive force in the world." },
  { id: "j19", category: "joy", text: "I embrace the magic of everyday moments." },
  { id: "j20", category: "joy", text: "I am worthy of all the good things happening to me." },

  // ───────────────────────────────────────────────────────────────────────
  // CREATIVITY
  // ───────────────────────────────────────────────────────────────────────
  { id: "cr1", category: "creativity", text: "My imagination is a powerful tool." },
  { id: "cr2", category: "creativity", text: "I have unique ideas that are worth sharing." },
  { id: "cr3", category: "creativity", text: "I give myself permission to make art just for fun." },
  { id: "cr4", category: "creativity", text: "There are no mistakes in my creative process." },
  { id: "cr5", category: "creativity", text: "I see the world through a colorful lens." },
  { id: "cr6", category: "creativity", text: "I am an original thinker." },
  { id: "cr7", category: "creativity", text: "My creativity flows effortlessly." },
  { id: "cr8", category: "creativity", text: "I trust my intuition to guide my expression." },
  { id: "cr9", category: "creativity", text: "I express myself freely and boldly." },
  { id: "cr10", category: "creativity", text: "My voice and my vision matter." },
  { id: "cr11", category: "creativity", text: "I am inspired by the beauty around me." },
  { id: "cr12", category: "creativity", text: "I turn my dreams into reality." },
  { id: "cr13", category: "creativity", text: "I am a creator, and my canvas is life." },
  { id: "cr14", category: "creativity", text: "I explore new ideas with curiosity." },
  { id: "cr15", category: "creativity", text: "It is safe for me to be different." },
  { id: "cr16", category: "creativity", text: "I celebrate my unique talents." },
  { id: "cr17", category: "creativity", text: "Thinking outside the box comes naturally to me." },
  { id: "cr18", category: "creativity", text: "Every day brings a chance to invent something new." },
  { id: "cr19", category: "creativity", text: "I am proud of the things I make." },
  { id: "cr20", category: "creativity", text: "I allow my mind to wander and dream." },
];
